language: python
python:
- '2.7'
install:
- pip install .
deploy:
  provider: pypi
  user: platform9
  password:
    secure: MZPBmxkuFOwdIU+p6/r/eLo3GXE0FFnVhmkM4qzx2Nva0vfUtF1rIZLaa3GK5U/OuGEVlxdnFnkHduyiZFNEvVBS8sEw1WXeItt7K+EBil6HQiWSA4YVHx/51Tra5W5qfZ/md9yBAtb2tFa12zvM/yDEtv/uFiWYG/rlx75OIm2glDdn13Wwre4i5kP0VrX050VMSR1eTrlQ3kkIabIIfQBkYYrLBtZpqZPGcsiHxFK6Lk7EVd8SPWnpdcfExWswmoeSlM3HS2G1Pzpy3Dvl4pVukp9h+TC9uGrV+FUPm7jvo7GEy4P2HAmHpFaKPMj7GcwQXOYBigXIxiB0f2/DYUoaZiB6V+gkvp2qd3AqJ6fScNOUTJ6UiuYXkPudyozQQ+prUZyOY101CfJpT/FUIUwHhnMOrgnw1yftymZrJyzSjY0fxJGcA6yAnPqkKzvnqLuQwoKMj7rZaHVq3ITpv6YOwYtuid8wmR2wNRPAPGGYzFMGfbRgzlgmTH5v0v5Ya4zhW8D4xYc0Tl+Vs/XstQxh4c1C5w6uP4ldEqqA6SI+ii7wpKJOKVKhGYMFcbbDOjC0S371ndCrWGaYqAKD64jmZ3pCXUyDXmRBHc2qy8fkgkH1snXJMqXS/ftC5QJI0TLOGN/GJD0KCtkiqiyNyQnxWDmqT0MmeEWHkLmsDcI=
  on:
    branch: ver-0.1
script:
- echo "Done"
